void main(){

  // Tentativa
  try{
    print("Executa uma função");
  }catch(erro){
    print("Falha ao executar: $erro");
  }

}